---
resource_types:
- name: maven
  type: docker-image
  source:
    repository: maven
    tag: 3-jdk-8
- name: cf-cli-resource
  type: docker-image
  source:
    repository: nulldriver/cf-cli-resource
    tag: latest
resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/ashwinpnr/SpringBootApplications.git
    branch: master
- name: artifact-repository
  type: s3
  source:
    bucket: ((bucket))
    region_name: ((bucket-region))
    access_key_id: ((key-id))
    secret_access_key: ((access-key))
    versioned_file: course-api-1.0-SNAPSHOT.jar

- name: cf-master
  type: cf-cli-resource
  source:
    api: ((cf-api))
    username: ((cf-username))
    password: ((cf-password))
    org: ((cf-org))
    space: development
    skip_cert_check: true
    
jobs:
  - name: package-app   
    plan:
      - get: source-code
        trigger: true
      - task: publish-code
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: 
              repository: maven
          inputs:
          - name: source-code
          outputs:
          - name: packaged-course-api
          run:
              path: sh
              args:
              - -exec
              - |
                ls
                cd ./source-code/course-api-service
                ls
                mvn clean install
                ls
                ls target/  
                cp target/course-api-1.0-SNAPSHOT.jar ../../packaged-course-api/
                ls  ../../packaged-course-api              
      - put: artifact-repository
        params:
          file: packaged-course-api/course-api-1.0-SNAPSHOT.jar
  - name: deploy-app
    plan:
        - get: artifact-repository
          trigger: true
        - put: cf-push
          resource: cf-master
          params:
            command: push
            app_name: ((course_api_app_name))
            path: artifact-repository/course-api-1.0-SNAPSHOT.jar
            


#fly -t ps set-pipeline -c course-api-deploy.yml -p course-api-deploy --load-vars-from creds.yml